### ISSUE TITLE
Array without key:value throws error in Document.php applyDecompression

### ISSUE THREAD

**Issue by ghost** [marcqualie/mongominify#1]
When using this schema:
return array(

```
    'id' => array(
            'short' => '_id'
    ),

    'username' => array(
            'short' => 'u'
    ),

    'password' => array(
            'short' => 'p'
    ),

    'roles' => array(
            'type' => 'enum',
            'short' => 'r',
            'values' => array(
                    0 => 'ROLE_ADMIN',
                    1 => 'ROLE_USER'
            )
    ),
```

);

With this example data:
{
  "_id": ObjectId("511ab5229624dd338b000000"),
  "p": "5FZ2Z8QIkA7UTZ4BYkoC+GsReLf569mSKDsfods6LYQ8t+a8EW9oaircfMpmaLbPBh4FOBiiFyLfuZmTSUwzZg==",
  "r": [
    0,
    1
  ],
  "u": "renedekat"
}

An error is thrown:

Warning: Invalid argument supplied for foreach() in /Users/renedekat/Sites/silex/vendor/marcqualie/mongominify/lib/MongoMinify/Document.php on line 150

**Comment by marcqualie** [comment]
Currently the library isn't designed to apply compression on the values, only the keys. I will look into providing this functionality as it would be a very popular use case.

As for storing arrays aswel as flat strings, that is currently supported and works in the same way without a schema change.
