### ISSUE TITLE
Hide php_network_getaddresses error when connection cannot be made.

### ISSUE THREAD

**Issue by scottrobertson** [marcqualie/mongominify#12]
Hide php_network_getaddresses error when connection cannot be made to allow for a cleaner try/catch. 

The try/catch works right now if you catch MongoConnectionException, however:

`Warning: MongoClient::__construct(): php_network_getaddresses: getaddrinfo failed: nodename nor servname provided, or not known in vendor/marcqualie/mongominify/lib/MongoMinify/Client.php on line 40`

Is outputted before the try catch. This error needs to be hidden somehow.

**Comment by scottrobertson** [comment]
I realise this could be the native mongo client doing this, but there must be a way.

**Comment by marcqualie** [comment]
I'll sort this today, thanks for reporting.

**Comment by marcqualie** [comment]
It doesn't look like there is a way to suppress this error from within the driver as it's part of the core php driver for mongodb, I suggested using an error handling library to catch warnings such as monolog.

**Comment by scottrobertson** [comment]
Yeah i figured it would be. Bit annoying.
