### ISSUE TITLE
Expecting string in aggregation

### ISSUE THREAD

**Issue by scottrobertson** [marcqualie/mongominify#7]
Passing an array as value in the children of $group is not allowed, but it should allow an array. See below for an example that should work, but doesn't:

I realise it's not the best example, but it gets my point across.

``` php
$ops = array(
    array(
        '$group' => array(
            '_id' => '$cookie_id',
            'search_engines' => array(
                '$push' => array(
                    'search_engine' => '$search_engine_id'
                )
            )
        ),
    )
);
$results = $collection->aggregate($ops);
```

Basically, the value of "search_engines" is required to be a string in mongominify, but an array is acceptable in the native mongo client. 

Scott

**Comment by marcqualie** [comment]
I've also seen this behaviour in certain cases. I will work on a fix.

**Comment by scottrobertson** [comment]
:+1: works.
